import { Language } from '@/hooks/language';
import { languageCodeToLanguage } from '@/lib/language';
import { debugLog, errorLog } from '@/logs';

export type TranscriptMetadata = {
  languageCode: string;
  isAutoGenerated: boolean;
  uiText: string;
  baseUrl: string;
  language: Language;
};

export type VideoMetadata = {
  title: string;
  duration: number;
  author: string;
  keywords: string[];
  shortDescription: string;
  channelId: string;
};

export type Caption = {
  startTime: number;
  endTime: number;
  text: string;
};

// Regex to parse the player response from the page
const YT_INITIAL_PLAYER_RESPONSE_RE =
  /ytInitialPlayerResponse\s*=\s*({.+?})\s*;\s*(?:var\s+(?:meta|head)|<\/script|\n)/;

function compareTracks(track1: any, track2: any) {
  const langCode1 = track1.languageCode;
  const langCode2 = track2.languageCode;

  if (track1.kind !== 'asr' && track2.kind === 'asr') {
    // asr: Automatic Speech Recognition
    return -1; // Non-ASR comes first
  } else if (track1.kind === 'asr' && track2.kind !== 'asr') {
    return 1; // Non-ASR comes first
  } else if (langCode1 === 'en' && langCode2 !== 'en') {
    return -1; // English comes first
  } else if (langCode1 !== 'en' && langCode2 === 'en') {
    return 1; // English comes first
  }

  return 0;
}

export const getVideoId = () => {
  return new URLSearchParams(window.location.search).get('v');
};

// The player's own timedtext request carries whatever this session needs to get captions
// (a pot token or not, depending on the account), so capture it whole instead of just the pot.
// Watching from the start means captions turned on earlier in the session spare the clicks below.
const playerCaptionUrls = new Map<string, string>();

export const watchPlayerCaptionRequests = () => {
  new PerformanceObserver((list) => {
    for (const entry of list.getEntries() as PerformanceResourceTiming[]) {
      // Skip our own caption fetches; the player requests them with XHR.
      if (!entry.name.includes('timedtext') || entry.initiatorType === 'fetch') continue;
      const videoId = new URL(entry.name).searchParams.get('v');
      if (videoId) {
        debugLog('[Youtube] watchPlayerCaptionRequests: entry', entry);
        playerCaptionUrls.set(videoId, entry.name);
      }
    }
  }).observe({ type: 'resource', buffered: true });
};

const getPlayerCaptionUrl = async (videoId: string): Promise<string | null> => {
  const knownUrl = playerCaptionUrls.get(videoId);
  if (knownUrl) return knownUrl;

  // No request for this video yet: toggle captions on and off so the player makes one.
  debugLog('[Youtube] getPlayerCaptionUrl: toggling captions for', videoId);
  const subtitlesButton = document.querySelector('.ytp-subtitles-button');
  if (subtitlesButton instanceof HTMLElement) {
    setTimeout(() => {
      subtitlesButton.click();
    }, 200);

    setTimeout(() => {
      subtitlesButton.click();
    }, 400);
  }

  for (let waited = 0; waited < 5000; waited += 100) {
    await new Promise((resolve) => setTimeout(resolve, 100));
    const url = playerCaptionUrls.get(videoId);
    if (url) return url;
  }
  return null;
};

// lang and kind are the only params that differ between a video's tracks, so swapping them
// (plus name/tlang) into the player's request keeps its auth params valid for any track.
const TRACK_PARAMS = ['lang', 'kind', 'name', 'tlang'];

const buildCaptionUrl = (trackBaseUrl: string, playerCaptionUrl: string | null) => {
  if (!playerCaptionUrl) {
    const url = new URL(trackBaseUrl);
    url.searchParams.set('c', 'WEB');
    url.searchParams.set('fmt', 'json3');
    url.searchParams.set('cplatform', 'DESKTOP');
    return url.toString();
  }

  const url = new URL(playerCaptionUrl);
  const trackParams = new URL(trackBaseUrl).searchParams;
  for (const key of TRACK_PARAMS) {
    const value = trackParams.get(key);
    if (value === null) {
      url.searchParams.delete(key);
    } else {
      url.searchParams.set(key, value);
    }
  }
  url.searchParams.set('fmt', 'json3');
  return url.toString();
};

export const getCaptionUrl = async (trackBaseUrl: string) => {
  const videoId = new URL(trackBaseUrl).searchParams.get('v') ?? '';
  return buildCaptionUrl(trackBaseUrl, await getPlayerCaptionUrl(videoId));
};

const getPlayerData = async (videoId: string) => {
  const pageData = await fetch(`https://www.youtube.com/watch?v=${videoId}`);
  const body = await pageData.text();
  const playerResponseMatch = body.match(YT_INITIAL_PLAYER_RESPONSE_RE);
  return playerResponseMatch ? JSON.parse(playerResponseMatch[1]) : null;
};

const getTranscriptMetadata = async (player: any): Promise<TranscriptMetadata[] | undefined> => {
  try {
    const tracks: any[] | undefined =
      player?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
    if (!tracks?.length) return;

    const sortedTracks = tracks.sort(compareTracks);

    const filteredTracks = sortedTracks.filter((t: any) => t.kind != 'asr');
    if (!filteredTracks.length && sortedTracks[0]) {
      filteredTracks.push(sortedTracks[0]);
    }

    const metadata = filteredTracks.map((track: any) => {
      return {
        languageCode: track.languageCode,
        isAutoGenerated: track.kind === 'asr',
        uiText: track.name?.simpleText ?? track.languageCode,
        baseUrl: track.baseUrl,
        language: languageCodeToLanguage(track.languageCode),
      } as TranscriptMetadata;
    });
    return metadata;
  } catch (error) {
    errorLog('[Youtube] getTranscriptMetadata: error', error);
    return;
  }
};

export const getVideoData = async (videoId: string) => {
  const player = await getPlayerData(videoId);
  if (!player) {
    errorLog('[Youtube] getVideoData: Unable to get player data');
    return { videoId };
  }
  const metadata: VideoMetadata = {
    title: player.videoDetails.title,
    duration: player.videoDetails.lengthSeconds,
    author: player.videoDetails.author,
    keywords: player.videoDetails.keywords,
    shortDescription: player.videoDetails.shortDescription,
    channelId: player.videoDetails.channelId,
  };

  debugLog('[Youtube] getVideoData: player', player);
  const transcriptMetadata = await getTranscriptMetadata(player);
  if (!transcriptMetadata) {
    debugLog('[Youtube] getVideoData: No transcript data found');
    return { videoId, metadata };
  }

  return { videoId, metadata, transcriptMetadata };
};
