// Generated by wxt
// Types for the #import virtual module
declare module '#imports' {
  export { browser, Browser } from 'wxt/browser';
  export { storage, StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage';
  export { useAppConfig } from 'wxt/utils/app-config';
  export { ContentScriptContext, WxtWindowEventMap } from 'wxt/utils/content-script-context';
  export { createIframeUi, IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe';
  export { createIntegratedUi, IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated';
  export { createShadowRootUi, ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root';
  export { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types';
  export { defineAppConfig, WxtAppConfig } from 'wxt/utils/define-app-config';
  export { defineBackground } from 'wxt/utils/define-background';
  export { defineContentScript } from 'wxt/utils/define-content-script';
  export { defineUnlistedScript } from 'wxt/utils/define-unlisted-script';
  export { defineWxtPlugin } from 'wxt/utils/define-wxt-plugin';
  export { injectScript, ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script';
  export { InvalidMatchPattern, MatchPattern } from 'wxt/utils/match-patterns';
  export { useState, useCallback, useMemo, useEffect, useRef, useContext, useReducer } from 'react';
  export { fakeBrowser } from 'wxt/testing';
  export { i18n } from '#i18n';
  export { defaultCurrentChat, currentChatAtom, useCurrentChat, currentThreadIdAtom, threadsAtom, CurrentChat } from '../src/hooks/chat';
  export { languageAtom, useLanguage, Language } from '../src/hooks/language';
  export { defaultModels, modelsAtom, useModels, Models } from '../src/hooks/models';
  export { useChromePortStream } from '../src/hooks/portStream';
  export { defaultSettings, settingsAtom, useSettings, Settings } from '../src/hooks/settings';
  export { default as streamingResponseStreamer } from '../src/hooks/streamingResponseStreamer';
  export { defaultUserMemory, userMemoryAtom, useUserMemory, loadUserMemory, UserMemory } from '../src/hooks/userMemory';
  export { hashStringToIndex } from '../src/utils/hash';
  export { db, addMessage, loadThread, listThreads, touchThread, createThread, Message, ThreadMeta } from '../src/utils/indexDB';
  export { overlayMenuItems } from '../src/utils/overlayMenu';
  export { getInitialSystemMessage, getInitialAIMessage } from '../src/utils/prompts';
  export { chromeStorageBackend } from '../src/utils/storageBackend';
  export { throttleTrailing } from '../src/utils/throttleTrailing';
  export { getOS } from '../src/utils/userOS';
  export { validateApiKey } from '../src/utils/validateApiKey';
}
