FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY shizue.json .
COPY main_server.py .
COPY gcs_utils.py .
COPY .env .

EXPOSE 8000

CMD ["uvicorn", "main_server:app", "--host", "0.0.0.0", "--port", "8000"]
