[mypy]
python_version = 3.11
warn_return_any = False
warn_unused_configs = False
disallow_untyped_defs = False
check_untyped_defs = False
ignore_missing_imports = True
allow_untyped_defs = True
allow_untyped_calls = True
no_implicit_optional = False
disable_error_code = import-untyped,attr-defined,call-arg,arg-type,return-value,misc,assignment,annotation-unchecked,union-attr

[mypy-loguru.*]
ignore_errors = True

[mypy-sqlalchemy.*]
ignore_missing_imports = True

[mypy-app.repositories.*]
allow_untyped_defs = True

[mypy-app.api.versioning.*]
allow_untyped_defs = True

[mypy-app.api.health.*]
allow_untyped_defs = True
